feat: first implementation
gemini-testing/hermione-passive-browsers pull request #2
Opened 2018-07-04 09:05 UTC by DudaGod

2018-07-04 10:26 UTC, j0tunn requested changes

2018-07-04 10:26 UTC, j0tunn commented on lib/config.js
> +                [_.isString, _.isRegExp, _.isArray],
зачем использовать лодашевские функции, если можно просто использовать просто `typeof`, тем более что он там в итоге все равно используется, и типы ты в нее все равно передаешь чуть ниже

2018-07-04 10:26 UTC, j0tunn commented on lib/config.js
> +const isOneOfRequestedType = (name, validationFns, types) => {
здесь не нужны две функции, просто сделай одну с возможностью передавать один или несколько типов. А для формирования сообщения об ошибке используй `must be ${types.join(' or ')}, but got ...`

2018-07-04 10:26 UTC, j0tunn commented on lib/config.js
> +            parseCli: JSON.parse,
я не уверен, что нужно давать возможность переопределять это через cli или через env

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +            'also',
здесь нужно использовать `config.commandName`

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +                in: hermione.isWorker() ? () => {} : function(matcher) {
не нужно этого делать на каждое событие. В мастере оно будет лететь один раз, а в воркере дофига раз. Лучше это условие проверить один раз при инициализации плагина и просто добавить правильные хендлеры

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +    const shouldRunTest = (test, browserId) => {
очень странно, что ты объявляешь эту функцию за пределами if'а, внутри которого она используется

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +                        runnablesToRun[browserId] = [].concat(runnablesToRun[browserId] || [], {id: this.id()});
зачем эту магию делать на каждый вызов `also`? Проинициализируй раз нужную структуру, а здесь просто допушивай.

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +                    if (shouldRunInBro(browserId, matcher)) {
зачем ты здесь что-то проверяешь, запушил всю инфу, а проверку будешь делать уже на `AFTER_TESTS_READ`, тем более, что ты ее итак там делаешь

2018-07-04 10:26 UTC, j0tunn commented on lib/index.js
> +        hermione.on(hermione.events.AFTER_TESTS_READ, (testCollection) => {
здесь нужно делать `prependListener`, чтобы всякие плагины типа `selective` не успели себе выгрести дерево до этого момента

2018-07-04 11:02 UTC, DudaGod commented on lib/index.js
> +            'also',
должно браться из конфига

2018-07-04 11:02 UTC, DudaGod commented on lib/config.js
> +                [_.isString, _.isRegExp, _.isArray],
потому что `typeof /foo/` -> `object` и `typeof []` ->  `object`

2018-07-04 11:23 UTC, j0tunn commented on lib/config.js
> +                [_.isString, _.isRegExp, _.isArray],
ну ок `val.constructor.name`

2018-07-04 12:43 UTC, j0tunn commented on README.md
> +* **commandName** (required) `String` - command name which will be added to hermione context and used in tests before test or suite declaration for enable test in passed browser; by default is `also`
Забыл убрать `bu default is also`

2018-07-04 12:44 UTC, j0tunn commented on README.md
> +    hermione.enable.in(['ie7', /ie[8,9]/]);
я правильно понимаю, что в ie6 этот тест тоже запустится?

2018-07-04 15:56 UTC, j0tunn requested changes
В общем давай перепишем на проход от корневых сьютов и включать будем тесты через объекты, а не через fullTitle

2018-07-04 15:56 UTC, j0tunn commented on lib/config.js
> +        const result = type.some((t) => v.constructor.name.toLowerCase() === t);
да ну зачем `toLowerCase`? Передавай просто правильные типы сюда

2018-07-04 15:56 UTC, j0tunn commented on lib/config.js
> +const isRequestedType = (name, type) => {
и да, это не `isRequestedType`, это `assertRequestedType`. Я уже ростику когда-то об этом писал: ты отсюда кидаешь исключение, а не просто bool возвращаешь

2018-07-04 15:56 UTC, j0tunn commented on lib/index.js
> +            return test.id && foundRunnable && shouldRunInBro(browserId, foundRunnable.matcher)
зачем здесь `test.id` проверять, если в `foundRunnable` это уже проверяется?

2018-07-04 21:58 UTC, tormozz48 commented on lib/config.js
> +const root = configParser.root;
```
const {root, section, option} = configParser;
```

2018-07-04 21:58 UTC, tormozz48 commented on lib/index.js
> +            if (!runnablesToRun[browserId]) {
`runnablesToRun[browserId] = runnablesToRun[browserId] || []`

2018-07-04 21:58 UTC, tormozz48 commented on lib/index.js
> +        if (!commandHandlers[browserId]) {
`commandHandlers[browserId] = commandHandlers[browserId] || commandHandlersFor(browserId);`

2018-07-04 21:58 UTC, tormozz48 commented on lib/index.js
> +            return test.id && foundRunnable && shouldRunInBro(browserId, foundRunnable.matcher)
Сложное условие. Можно было бы разбить на 2 или хотя бы сгруппировать с помощью скобок.
```js
return (foundRunnable && shouldRunInBro(browserId, foundRunnable.matcher)) || (test.parent && shouldRunTest(test.parent, browserId));
```

2018-07-04 21:58 UTC, tormozz48 commented on test/lib/config.js
> +        describe('should does not throw error if an option set as', () => {
А если задать массив, например с числами или чем-то другим (не регулярка и не строка), то что будет?

2018-07-06 06:17 UTC, DudaGod commented on test/lib/config.js
> +        describe('should does not throw error if an option set as', () => {
Я не проверяю значения массива. Если в массиве передать числа, то ничего не упадет. Так как я просто не найду браузеры в конфиге которые называются так же само.

2018-07-06 09:28 UTC, DudaGod commented on lib/index.js
> +                if (_.isEmpty(suitesToRun[browserId]) && _.isEmpty(testsToRun[browserId])) {
эту проверку нужно делать сразу после `disableAll`, а не для каждого теста в этом браузере

2018-07-06 14:52 UTC, j0tunn requested changes

2018-07-06 14:52 UTC, j0tunn commented on README.md
> +Example of enable tests in passive browsers:
Напиши тут просто `Example:`

2018-07-06 14:52 UTC, j0tunn commented on README.md
> +    hermione.enable.in(/ie[10,11]/);
Димооооон. Перечитай доку по регэкспам

2018-07-06 14:52 UTC, j0tunn commented on README.md
> +    it('test3', () => {...});
если написать стрелочную функцию, то внутри к `this.browser` не обратишься. Может писать через `function` в примере?

2018-07-06 14:52 UTC, j0tunn commented on lib/config.js
> +const _ = require('lodash');
ты eslint не настраивал? `_` в этом файле не используется

2018-07-06 14:52 UTC, j0tunn commented on lib/index.js
> +            testCollection.eachTest(browserId, (test) => _.extend(test, {disabled: true}));
а зачем ты это отдельно делаешь? зачем два прохода?
делай в один проход:
```js
testCollection.eachTest(browserId, (test) => test.disabled = shouldRunTest(test))
```

2018-07-06 14:52 UTC, j0tunn commented on lib/index.js
> +    const shouldRunTest = (runnable, browserId, storage) => {
- эту функцию можно объявлять внутри `passiveBrowserIds`, тогда не придется `browserId` передавать
- можно указать `testsToRun` в качестве дефолтного `storage`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/config.js
> +    const mkConfig_ = (opts = {}) => _.defaults(opts, {commandName: 'default-command'});
тяжело читать такие однострочники

2018-07-06 14:52 UTC, j0tunn commented on test/lib/config.js
> +        describe('should does not throw error if an option set as', () => {
`does` здесь лишнее: `should not throw`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/config.js
> +    const mkConfig_ = (opts = {}) => _.defaults(opts, {commandName: 'default-command'});
эта функция всегда используется внутри `parseConfig`, сделал бы `parseConfig_`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/config.js
> +    const mkConfig_ = (opts = {}) => _.defaults(opts, {commandName: 'default-command'});
а почему здесь не используется `mkConfig_` из `utils`?

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +    const emitBeforeFileRead = (browsers = 'default-bro') => {
объявляй переменные и функции максимально близко к месту использования. В данном случае можно объявить внутри дескрайба `working with tests tree`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +        it('should be enabled by default', () => {
зачем этот тест здесь? Ты уже протестировал в конфиге, что он enabled by default

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +    const emitBeforeFileRead = (browsers = 'default-bro') => {
вообще кажется, что эти функции лишние. Без них тесты будут читаться проще. И не нужны будут эти полуглобальные переменные `hermione` и  `testParser`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +                // order is important for test prependListener
этот комментарий тут ни к чему

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +                const testHandler = sandbox.spy().named('testHandler');
это собственно `spy`, он и по смыслу должен называться `spy`

2018-07-06 14:52 UTC, j0tunn commented on test/lib/index.js
> +                });
```js
hermione.on(hermione.events.AFTER_TESTS_READ, (testCollection) => testCollection.eachTest(testHandler));
```
Здесь не важно для какого браузера будет позван `eachTest`

А ниже просто проверяешь через `sinon.match({disabled: true})`

2018-07-06 14:54 UTC, DudaGod commented on lib/config.js
> +const _ = require('lodash');
хм, странно. Настраивал

2018-07-06 15:15 UTC, DudaGod commented on lib/index.js
> +    const shouldRunTest = (runnable, browserId, storage) => {
так у меня же там `forEach` по пассивным браузерам. Получается функция `shouldRunTest` для каждого браузера будет инициализироватся по новой

2018-07-06 15:29 UTC, DudaGod commented on lib/index.js
> +            testCollection.eachTest(browserId, (test) => _.extend(test, {disabled: true}));
Думал, что быстрее будет за счет проверки, которая у меня ниже находится:
```js
if (_.isEmpty(suitesToRun[browserId]) && _.isEmpty(testsToRun[browserId])) {
    return;
}
```

2018-07-06 15:51 UTC, DudaGod commented on test/lib/index.js
> +    const emitBeforeFileRead = (browsers = 'default-bro') => {
ок, но тесты тогда значительно больше получаться

2018-07-06 21:24 UTC, j0tunn commented on lib/index.js
> +    const shouldRunTest = (runnable, browserId, storage) => {
да, и это нормально, так как она будет инициализироваться с замыканием, в котором будет браузер. Каждый раз свой

2018-07-06 21:25 UTC, j0tunn commented on test/lib/index.js
> +    const emitBeforeFileRead = (browsers = 'default-bro') => {
ничего страшного, лишь бы читались легко

2018-07-07 10:35 UTC, DudaGod commented on test/lib/index.js
> +                });
Согласен, но ведь `eachTest` это мой простой стаб который выглядит так:
```js
const mkTestCollection = (testsTree) => ({eachTest: (bro, cb) => testsTree[bro].forEach(cb)});
```

И в коде я зову `eachTest` именно с передачей браузера. Если в тестах звать без него, то нужно стаб усложнять:
```js
(bro, cb) => {
  if (!cb) {
    cb = bro;

    return _.flatten(_.values(testsTree)).forEach(cb);
  }

  return testsTree[bro].forEach(cb);
}
```
Возможно можно чуть проще написать, но в любом случае прийдется значительно усложнить стаб.

Я бы оставил с передачей браузера.

2018-07-09 05:57 UTC, j0tunn approved these changes

2018-07-09 05:57 UTC, j0tunn commented on README.md
> +    hermione.enable.in(/ie1[0,1]/);
Димон! https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp

2018-07-09 05:57 UTC, j0tunn commented on test/lib/utils.js
> +exports.stubTest_ = ({id = 'test-id', parent} = {}) => ({id: () => id, parent});
не надо писать в одну строчку выражение, где больше одной функции. Это плохо читается

2018-07-09 14:08 UTC, merged